configs:
- id: profile
  config:
    name: Star Trek Service
    template: profile.json
    skip: false
  type:
    api: alerting-profile

- id: another-profile
  config:
    name: 'Star Trek II: The Wrath of Code Dept'
    template: profile.json
  type:
    api:
      name: alerting-profile #monaco-test:no-replace
